[package]
name = "rust-dwm-status"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]

[dependencies]
chrono = "*"
systemstat = { git = "https://github.com/pierrechevalier83/systemstat.git" }
